id: ADF0F4DA3
title: ยง28
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:55:40.972835
  last_modified_at: 2022-03-01 21:55:40.972838
