id: ADF0F4DA3
title: CVII_d
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:55:40.885635
  last_modified_at: 2022-03-01 21:55:40.885638
