id: ADF0F4DA3
title: ยง8
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:55:40.992465
  last_modified_at: 2022-03-01 21:55:40.992468
