id: ADF0F4DA3
title: CXIII_a
type: translation
source_metadata:
  languages:
  - zh
  - bo
  - sa
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:55:40.912718
  last_modified_at: 2022-03-01 21:55:40.912721
